### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by XhmikosR**
@yargalot: don't merge this yet, still compressing the image. I wonder, should we have the image in AccessSniff only instead of duplicating it?

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oh, another thing. Is the example valid anymore? Should it be in the repo?

**Comment by yargalot** [comment]
Yeh example wouldnt be relevant anymore I think, gonna have to change it with the new architecture

**Comment by XhmikosR** [comment]
OK, branch updated. I'll leave the example to you.

Please make a new release after this goes and you fix the remaining issues :)

**Comment by yargalot** [comment]
Yep will do, thanks for all the updates, will update the rest and release it over the weekend :)

**Comment by XhmikosR** [comment]
@yargalot: this should be mergeable now. I left the AccessSniff update for another branch.

**Comment by yargalot** [comment]
And New release is out :) https://github.com/yargalot/grunt-accessibility/releases/tag/v4.0.0

**Pull request merged**
